[workspace]
members = ["fmo_api_types", "fmo_frontend", "fmo_server"]

resolver = "2"

[workspace.dependencies]
fedimint-core = { git = "https://github.com/fedibtc/fedimint", tag = "v0.7.0-fedi2" }
fedimint-api-client = { git = "https://github.com/fedibtc/fedimint", tag = "v0.7.0-fedi2" }
fedimint-ln-common = { git = "https://github.com/fedibtc/fedimint", tag = "v0.7.0-fedi2" }
fedimint-mint-common = { git = "https://github.com/fedibtc/fedimint", tag = "v0.7.0-fedi2" }
fedimint-wallet-common = { git = "https://github.com/fedibtc/fedimint", tag = "v0.7.0-fedi2" }
